<?php $title = "netrek-client-pygame"; include('../header.inc'); ?>
A Netrek client, using pygame<br>
by James Cameron, 2010-03-24<p>

<h3>Synopsis</h3>

How to begin playing Netrek using only a Python and Pygame software
configuration, on any operating system supported by them.<p>

Package is a game client program with images derived from other Netrek
clients.<p>

<h3>Resources</h3>

<ul>

<li><a
href="netrek-client-pygame-0.5.tar.gz">netrek-client-pygame-0.5.tar.gz</a>
source release,

<li><a href="https://launchpad.net/netrek-client-pygame">launchpad netrek-client-pygame</a>,

<li><a
href="http://james.tooraweenah.com/darcs/netrek-client-pygame/">http://james.tooraweenah.com/darcs/netrek-client-pygame/</a>
source repository (darcs),

<li><a href="http://james.tooraweenah.com/cgi-bin/darcs.cgi/netrek-client-pygame/?c=patches">source repository changes</a>

<li><a href="http://james.tooraweenah.com/cgi-bin/darcs.cgi/netrek-client-pygame/?c=rss"><img src="rss.gif"></a>, RSS feed for source repository changes,

<li><a href="http://www.netrek.org/">www.netrek.org</a>,
<li><a href="http://www.python.org/">www.python.org</a>,
<li><a href="http://www.pygame.org/">www.pygame.org</a>.
</ul>

<h3>Screenshots</h3>

<center>
<img src="0.5-splash.jpg" width="800" height="800"><p>
<img src="0.5-tips.jpg" width="800" height="800"><p>
<img src="0.5-servers.jpg" width="800" height="800"><p>
<img src="0.5-login.jpg" width="800" height="800"><p>
<img src="0.5-outfit.jpg" width="800" height="800"><p>
<img src="0.5-action-0004.jpg" width="800" height="800"><p>
<img src="0.5-action-0010.jpg" width="800" height="800"><p>
<img src="0.5-action-0011.jpg" width="800" height="800"><p>
<img src="0.5-action-0021.jpg" width="800" height="800"><p>
<img src="0.5-action-0022.jpg" width="800" height="800"><p>
<img src="0.5-action-0023.jpg" width="800" height="800"><p>
</center>

<h3>Hacking</h3>

Get the source:<p>

<pre>
sudo aptitude install darcs
darcs get http://james.tooraweenah.com/darcs/netrek-client-pygame/
</pre>

Read the netrek/__init__.py file and start making interesting changes.<p>

See what you have changed:<p>

<pre>
darcs diff
</pre>

Record and send what you have changed:<p>

<pre>
darcs record
darcs send
</pre>

<h3>Prototype History</h3>

This is a change log from a repository that was used before the
current respository.  It shows how easy it was to create code to do
something in Pygame.<p>

<pre>
Sat Jun 23 23:19:15 EST 2007  quozl@us.netrek.org
  * add team specific planets

Sat Jun 23 21:20:16 EST 2007  quozl@us.netrek.org
  * default to tactical, isolate reference data, cloak, outfit rejig

Sat Jun 23 17:32:34 EST 2007  quozl@us.netrek.org
  * move shields to sprite, identify torps by team

Sat Jun 23 12:56:33 EST 2007  quozl@us.netrek.org
  * add planet flags, pfiredist ring, font cache

Wed Jun 20 23:09:19 EST 2007  quozl@us.netrek.org
  * add tractor and ship lock

Wed Jun 20 22:07:50 EST 2007  quozl@us.netrek.org
  * add --host, time based torpedo explosion timeout, shields

Tue Jun 19 22:41:41 EST 2007  quozl@us.netrek.org
  * simplify mainline, add orion tactical iconography

Tue Jun 19 19:01:27 EST 2007  quozl@us.netrek.org
  * add galactic ship iconography for testing
  	Add 8x8 iconography on galactic for testing, better images expected
  	later on in development.

Tue Jun 19 18:50:00 EST 2007  quozl@us.netrek.org
  * add torp explosions, fix ship ghosting, add det
  	Add torpedo explosions.
  	Fix ship ghosting caused by ships that change direction not position.
  	Add det others and det own keys.
  	Add practice robot call key.
  	Add orbit key.
  	Add slot number over ship on tactical.
  	Split tactical animation into separate sprite groups.

Mon Jun 18 21:48:29 EST 2007  quozl@us.netrek.org
  * add ship explosions

Mon Jun 18 21:10:34 EST 2007  quozl@us.netrek.org
  * add phaser animation

Fri Jun 15 19:37:31 EST 2007  quozl@us.netrek.org
  * add tactical animation of torps

Fri Jun 15 18:59:04 EST 2007  quozl@us.netrek.org
  * tactical or galactic navigation, right click set course

Fri Jun 15 18:37:35 EST 2007  quozl@us.netrek.org
  * class inversion, tactical flight capability
  * split sprite and netrek data into separate classes

Wed Jun 13 22:03:16 EST 2007  quozl@us.netrek.org
  * add metaserver phase

Tue Jun 12 18:39:11 EST 2007  quozl@us.netrek.org
  * add remaining packet types

Mon Jun 11 21:18:45 EST 2007  quozl@us.netrek.org
  * repair, shield, login dialog
  * display modes

Sun Jun 10 21:56:43 EST 2007  quozl@us.netrek.org
  * ideas

Sun Jun 10 14:56:44 EST 2007  quozl@us.netrek.org
  * bomb, beam, cloak

Sat Jun  9 23:18:56 EST 2007  quozl@us.netrek.org
  * oysters open and closed

Sat Jun  9 17:19:30 EST 2007  quozl@us.netrek.org
  * add planet lock and automatic join
  * add license
  * convert to sprite usage

Wed Jun  6 16:55:36 EST 2007  quozl@us.netrek.org
  * scout can fly to rom and ghostbust

Wed Jun  6 14:12:21 EST 2007  quozl@us.netrek.org
  * warp zero flight achieved

Wed Jun  6 12:44:08 EST 2007  quozl@us.netrek.org
  * progress, to team selection point

Tue Jun  5 23:24:49 EST 2007  quozl@us.netrek.org
  * test python client, to login phase

Tue Jun  5 23:16:54 EST 2007  quozl@us.netrek.org
  * test python client
</pre>

<?php include('../footer.inc'); ?>
