<?php
if (preg_match('/gytha/', $_SERVER['REQUEST_URI'])) {
    $title = 'gytha';
} else {
    $title = 'netrek-client-pygame';
}
include('../header.inc'); ?>

gytha, a Netrek client,<br>
by James Cameron, 2010-11-07<p>

<h3>Introduction</h3>

Netrek is a multi-player real-time 2D strategy game.
<sup><a href="http://netrek.org">[1]</a>
<a href="http://en.wikipedia.org/wiki/Netrek">[2]</a></sup><p>

Your team starts with ten planets.  Each player flies a starship.  You
shoot at enemy ships with torpedos and phasers.  You fly to, scan and
bomb enemy planets to deny their use by the enemy team.  You protect
your own planets by preventing the enemy from reaching them.<p>

Once you make a kill, and don't die, you beam up armies from the
planets you protected, and drop them on the enemy planets that have
been bombed.<p>

Your team wins when all the enemy planets are taken.  Your team loses
if all your planets are taken from you.  Strategies include escorting,
controlling space, and coordinated attacks.<p>

<a name="downloads"><h3>Downloads</h3></a>

<h4>Microsoft Windows - 32-bit</h4>

Download and run the installer <a
href="http://netrek.org/files/netrek-client-pygame/gytha-0.6.1-win32.exe">gytha-0.6.1-win32.exe</a>.<p>

If you are not sure, try 32-bit first.<p>

<h4>Microsoft Windows - 64-bit</h4>

Download and run the installer <a
href="http://netrek.org/files/netrek-client-pygame/gytha-0.6.1-win64.exe">gytha-0.6.1-win64.exe</a>.<p>

<h4>Mac OS X</h4>

None available yet.  To contribute a build, please write to me.

<h4>Linux</h4>

<ul>
<li>install dependencies
<pre>
apt-get install python-pygame ttf-dejavu-core
</pre>
<p>
<li>download the source release (see below)
<li>unpack it
<li>run the file <i>netrek-client-pygame</i>
</ul>

<h3>What is it?</h3>

Gytha is a client for Netrek.  It is multiplatform, in that it works
on multiple operating systems.<p>

<a name="resources"><h3>Resources</h3></a>

<ul>

<li><a
href="<?php echo $title;?>-0.6.1.tar.gz"><?php echo $title;?>-0.6.1.tar.gz</a>
source release,

<li><a href="https://launchpad.net/netrek-client-pygame">launchpad netrek-client-pygame</a>,

<li><a
href="http://james.tooraweenah.com/darcs/netrek-client-pygame/">http://james.tooraweenah.com/darcs/netrek-client-pygame/</a>
source repository (darcs),

<li><a href="http://james.tooraweenah.com/cgi-bin/darcsweb.cgi?r=netrek-client-pygame;a=summary">source repository changes</a> <a href="http://james.tooraweenah.com/cgi-bin/darcsweb.cgi?r=netrek-client-pygame;a=rss"><img src="rss.gif"></a>,

<li><a href="http://www.netrek.org/">www.netrek.org</a>
</ul>

<a name="screenshots"><h3>Screenshots</h3></a>


<h4>Splash</h4>
<center><table width="810" border="0"><tr><td>
A splash screen, containing the name of the game, a license, and a
rotating icon.  During this time the imagery pipeline is stabilised,
and graphical assets are loaded.<p>

What you do: wait.<p>

<img src="0.7-splash.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Servers</h4>
<center><table width="810" border="0"><tr><td>
A list of available Netrek servers is displayed, discovered on the
local area network, or via the internet based metaservers.  Against
each server is a number of squares corresponding to how many players
are on the server.<p>

A pair of white objects are in orbit around each other above the list;
when they pass close to each another the metaserver is checked
again.<p>

What you do: choose a server and left-click on it to log in, or
middle-click on it to join the game as a guest mercenary.<p>

<img src="0.7-servers.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Tips</h4>
<center><table width="810" border="0"><tr><td>
A list of helpful hints, or tips, on how to get started.<p>

What you do: read them, then click on <i>Server List</i>.<p>

<img src="0.7-tips.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Login</h4>
<center><table width="810" border="0"><tr><td>
A server login screen.  Shows the name of the server you have
connected to, the server message of the day, and asks you for your
name.<p>

What you do: read the message of the day.  Type guest and press enter
if you do not want your statistics saved, or type a name and password.
If someone else has already used your name, you won't be able to use
it unless you know their password.<p>

<img src="0.7-login.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Ship and Race</h4>
<center><table width="810" border="0"><tr><td>
The ship and race, or team selection screen.  Shows ships for each
team you can join.<p>

What you do: choose a ship and race by clicking on one of the ships.
The ship closest to the centre is the best general ship, called a
Cruiser (CA).  The others have special improvements and weaknesses.
Some ships aren't available on some servers.  All ships of the same
type are equal regardless of which race or team you choose.<p>

<img src="0.7-outfit.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Tactical View</h4>
<center><table width="810" border="0"><tr><td>
The tactical view.  Your ship is in the centre.  A ring around your
ship shows your shields are up.<p>

Also on this view are:
<ul>
<li>ship warnings, in red on the top of screen,
<li>game messages, from the server or other players, in the top half
of the screen blended with the background so you are not distracted,
<li>a planet Beta Crucis that is not yet scanned, so we don't know
what team owns it,
<li>your ship in the middle, ship number 8, with two torpedo
explosions on the right hand side, with phasers shooting at enemy ship
number 3,
<li>your torpedos that missed the enemy ship 3 are flying away,
<li>the status line, showing Speed 3, Fuel 6193, Damage 73%, Shields
1%, Weapon Temperature 8, and various flags.
</ul>

What do you: play.  Various keyboard keys do various things.  See the
tips screenshot for more information.<p>

<img src="0.5-action-0004.jpg" width="800" height="800"><p>
</td></tr></table></center>


<h4>Galactic View</h4>
<center><table width="810" border="0"><tr><td>
Press enter to swap to the galactic view.  Your ship is in the centre
of the small white box.  The other boxed areas are teams or races.
The circles are the planets.  In this screenshot, you goal in the game
is to take control of the red Romulan team planets.<p>

Also on this view are:
<ul>
<li>the planets have a number above them; this is the number of armies present,
<li>the planets have a name below them; the colour shows which team
they belong to, and the bright colour means they have more than four
armies, therefore they can be bombed or used by their owning team as a
source of armies for taking other planets,
<li>the other ships show as tiny icons moving about.
</ul>

What do you: play.  All the same keyboard and mouse actions do the
same thing, just that you can't see as much detail.<p>
<img src="0.5-galactic.jpg" width="1000" height="1000"><p>
</td></tr></table></center>


<h4>Other Tactical Views</h4>
<center><table width="810" border="0"><tr><td>
The white burst is a torpedo that has just exploded, it it has caused
your damage to exceed 100%, so your ship has started to explode.  The
coloured ring around your ship is the start of the explosion.  The
green dots are more torpedos from the enemy that would have hit had
you survived.<p>
<img src="0.5-action-0010.jpg" width="800" height="800"><p>
A short time later, your explosion has engulfed the enemy ship as it
expands.  This damages the enemy, though not always fatally.  Your
death is not in vain.  You will be returned to the team and ship
screen from which you would normally come straight back in with the
spacebar.  The supply of new ships is endless until your team runs out
of planets.<p>
<img src="0.5-action-0011.jpg" width="800" height="800"><p>
Another three screenshots of a death are below; you have fired a
phaser which missed, and the enemy ship number 4 has killed you with a
torpedo and a phaser at the same time.  That ship is caught in the
blast radius and damaged, though not fatally.<p>
<img src="0.5-action-0021.jpg" width="800" height="800"><p>
<img src="0.5-action-0022.jpg" width="800" height="800"><p>
<img src="0.5-action-0023.jpg" width="800" height="800"><p>
</td></tr></table></center>



<a name="hacking"><h3>Hacking</h3></a>

Get the source:<p>

<pre>
sudo aptitude install darcs
darcs get http://james.tooraweenah.com/darcs/netrek-client-pygame/
</pre>

Read the netrek/__init__.py file and start making interesting changes.<p>

See what you have changed:<p>

<pre>
darcs diff
</pre>

Record and send what you have changed:<p>

<pre>
darcs record
darcs send
</pre>

<a name="building"><h3>Building and Packaging</h3></a>

On Linux, no building is required, gytha will run from your copy of
the source.  Packaging for Linux distributions is welcome, please
write to me.<p>

For Microsoft Windows developers, see <a
href="build-on-windows.phtml">building on windows</a> which was copied
from <a href="http://gytha.oggthebase.org/">Zachary Uram's page</a>.<p>

<?php include('../footer.inc'); ?>
