<?php $title = "netrek-client-pygame"; include('../header.inc'); ?>
A Netrek client, using pygame<br>
by James Cameron, 2007-06-24<p>

<h3>Synopsis</h3>

How to begin playing Netrek using only a Python and Pygame software
configuration, on any operating system supported by them.<p>

Package is a game client program with images derived from other Netrek
clients.<p>

<h3>Resources</h3>

<ul>

<li><a
href="netrek-client-pygame_0.2-1_i386.deb">netrek-client-pygame_0.2-1_i386.deb</a>
"binary" release for Debian GNU/Linux,

<li><a
href="netrek-client-pygame-0.2.tar.gz">netrek-client-pygame-0.2.tar.gz</a>
source release,

<li><a
href="http://james.tooraweenah.com/darcs/netrek-client-pygame/">http://james.tooraweenah.com/darcs/netrek-client-pygame/</a>
source repository (darcs),

<li><a href="http://james.tooraweenah.com/cgi-bin/darcs.cgi/netrek-client-pygame/?c=patches">source repository changes</a>

<li><a href="http://james.tooraweenah.com/cgi-bin/darcs.cgi/netrek-client-pygame/?c=rss"><img src="rss.gif"></a>, RSS feed for source repository changes,

<li><a href="http://www.netrek.org/">www.netrek.org</a>,
<li><a href="http://www.python.org/">www.python.org</a>,
<li><a href="http://www.pygame.org/">www.pygame.org</a>.
</ul>

<h3>Screenshots, Splash, Servers, Login and Outfit, version 0.2</h3>

<center>
<img src="0.2-splash.jpg"><p>
<img src="0.2-servers.jpg"><p>
<img src="0.2-login.jpg"><p>
<img src="0.2-outfit.jpg"><p>
</center>

<p><i>(prepared using the --screenshots option in 0.3 which takes a snapshot
in TGA format, then manual "convert -quality 60 input.tga output.jpg")</i></p>

<h3>Screenshots, Tactical, version 0.1</h3>

<center>
<img src="0.1-a.png"><p>
<img src="0.1-b.png"><p>
<img src="0.1-c.png"><p>
<img src="0.1-d.png"><p>
</center>

<p><i>(prepared using the "escape" key in 0.2 which takes a snapshot
in TGA format, then manual "convert input.tga output.png" and "pngnq
input.png output.png")</i></p>

<?php include('../footer.inc'); ?>
